s = set([1, 2, 3])
t = set([3, 4, 5])
print('La unión de los sets s y t, es: {}'.format(s.union(t)))
print('La intersección entre los sets s y t, es: {}'.format(s.intersection(t)))
print('La diferencia de s, respecto a t, es: {}'.format(s.difference(t)))
print('La diferencia de t, respecto a s, es: {}'.format(t.difference(s)))